#!/bin/bash

URL="https://pokeapi.co/api/v2/pokemon/"
POKEMON_NAME="pikachu"
DATA_FILE="data.json"
ERROR_FILE="errors.txt"

response=$(curl -s $URL$POKEMON_NAME)
if [ $? -ne 0 ]; then
    echo "Error: Could not get data from $URL$POKEMON_NAME" >> $ERROR_FILE
    exit 1
fi

echo $response | jq '.' > $DATA_FILE
echo "Data saved to $DATA_FILE"