#!/bin/bash
# Parse data from a JSON file and output a formatted string

DATA_FILE="data.json"

function capitalize() {
    echo $1 | awk '{print toupper(substr($0, 1, 1)) tolower(substr($0, 2))}'
}

# Parse the data
pokemon_name=$(jq -r '.name' $DATA_FILE)
pokemon_height=$(jq -r '.height' $DATA_FILE)
pokemon_weight=$(jq -r '.weight' $DATA_FILE)
pokemon_type=$(jq -r '.types[0].type.name' $DATA_FILE)

printf "%s is of type %s, weighs %dkg, and is %.1fm tall.\n" "$(capitalize $pokemon_name)" "$(capitalize $pokemon_type)" $((pokemon_weight/10)) $((10 * pokemon_height / 10))e-1