#!/bin/bash
# Parse data from a JSON file and output a formatted string

DATA_FILE="data.json"

function capitalize() {
    echo $1 | sed 's/./\U&/'
}

# Parse the data
name=$(capitalize $(jq -r '.name' $DATA_FILE))
pokemon_height=$(jq -r '.height' $DATA_FILE)
pokemon_weight=$(jq -r '.weight' $DATA_FILE)
type=$(capitalize $(jq -r '.types[0].type.name' $DATA_FILE))

formatted_height=$(awk "BEGIN {printf \"%.1f\", $pokemon_height / 10}")
formatted_weight=$((pokemon_weight / 10))

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."